[package]
name = "hprof-cli"
version = "0.1.0"
edition = "2021"
description = "CLI for exploring V8 memory profiles"
license = "MIT"

[[bin]]
name = "hprof"
path = "src/main.rs"

[dependencies]
hprof-core = { path = "../hprof-core" }
serde_json = { workspace = true }
regex = "1"

[lints]
workspace = true
